#!/bin/bash
#BungeeCord startup script
echo 'Starting up BungeeCord'
echo 'Startup version 1.3'

NOW=$(date +"%m-%d-%y-%r")
FILE="$NOW.tar.gz"

echo 'Deleting old BungeeCord.jar'

rm "$HOME/BungeeCord.jar"

echo 'Done!'

echo 'Archiving Old Log Files'

tar cvzf "$HOME/log/BungeeCord/$NOW.tar.gz" "$HOME/BungeeCord/proxy.log.0"
rm "$HOME/BungeeCord/proxy.log.0"
echo 'Done...'

echo 'Deleting Old Log Files'

rm "$HOME/BungeeCord/proxy.log.0.lck"
echo 'Done...'

echo 'All clean!'

echo 'Hold on while I grab the latest jar in /jar'
cp "$HOME/jar/BungeeCord.jar" "$HOME/BungeeCord/BungeeCord.jar"

echo 'Ok lets continue with startup'

"$HOME/BungeeCord/start.sh"